# Generated by Django 5.1.7 on 2025-03-18 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0001_initial"),
        ("tournament", "0002_tournament_end_date_tournament_max_players_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournament_wins",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentmatch",
            name="next_match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_match",
                to="matches.match",
            ),
        ),
    ]
