# Generated by Django 5.1.7 on 2025-03-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_alter_tournamentplayer_user"),
        ("users", "0003_userprofile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentplayer",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tournament_entries",
                to="users.userprofile",
            ),
        ),
    ]
