# Generated by Django 5.1.7 on 2025-03-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoreboard", "0003_alter_match_away1"),
        ("users", "0003_userprofile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="away1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away1_matches",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="away2_matches",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home1_matches",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="home2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home2_matches",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_winner1",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="match_winner2",
                to="users.userprofile",
            ),
        ),
    ]
