# Generated by Django 5.1.7 on 2025-03-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoreboard", "0004_alter_match_away1_alter_match_away2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="ad",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="match_tiebreak",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="match",
            name="max_sets",
            field=models.IntegerField(default=3),
        ),
    ]
