# Generated by Django 5.1.7 on 2025-03-09 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scoreboard", "0005_alter_match_ad_alter_match_match_tiebreak_and_more"),
        ("users", "0003_userprofile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="home1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="home1_matches",
                to="users.userprofile",
            ),
        ),
    ]
