# Generated by Django 5.1.7 on 2025-03-16 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communityusers",
            options={"verbose_name_plural": "Community Users"},
        ),
        migrations.AlterUniqueTogether(
            name="communityusers",
            unique_together={("community", "user")},
        ),
    ]
