# Generated by Django 5.1.7 on 2025-04-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_communityusers_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityusers",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                    ("pending_invitation", "Pending Invitation"),
                    ("pending_request", "Pending Request"),
                ],
                default="member",
                max_length=25,
            ),
        ),
    ]
