# Generated by Django 5.1.7 on 2025-03-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_alter_communityusers_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityusers",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("moderator", "Moderator"),
                    ("admin", "Admin"),
                    ("owner", "Owner"),
                    ("pending admin acceptance", "Pending Admin Acceptance"),
                    ("pending invitation", "Pending Invitation"),
                ],
                default="member",
                max_length=25,
            ),
        ),
    ]
